spring:
  application:
    name: Product-service
  h2:
    console:
      path: /database
      enabled: true
  datasource:
    username: root
    password: root
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./database/data